### ISSUE TITLE
IOS devices do not respond to multiple information polls

### ISSUE THREAD

**Issue by rdragonz** [nlMeminger/MagiCarp#4]
When connected to an IOS device, the song information flashes briefly and then disappears on the next poll for song information, and then stays blank until the song changes.

This is currently a high-priority issue due to the nature of the bug, and should be addressed as soon as possible.

**Comment by rdragonz** [comment]
Information update:

This appears to be a glitch solely with Spotify on IOS, using other applications such as Soundcloud and YouTube music does not produce the same result

**Comment by nlMeminger** [comment]
Confirmed, this was an issue with Spotify on ios.  The dbus exposed by spoitfy for whatever reason only shared the song information briefly, and the way things were we were constantly polling for song info.  New logic has been added that checks if the new song info matches the old or not, or if the song info is empty.  If not empty and not a match, then the info is changed on screen.  Tis bug is fixed in #12
